### ISSUE TITLE
Reliable Federated XGBoost

### ISSUE THREAD

**Issue by YuanTingHsieh** [NVIDIA/NVFlare#2388]
Contents modified from @yanchengnv 

**Is your feature request related to a problem? Please describe.**
XGBoost (https://github.com/dmlc/xgboost) is an open-source project that implements machine learning algorithms under the [Gradient Boosting](https://en.wikipedia.org/wiki/Gradient_boosting) framework. It is an optimized distributed gradient boosting library designed to be highly efficient, flexible and portable.

This implementation uses MPI (message passing interface - https://en.wikipedia.org/wiki/Message_Passing_Interface) for client communication and synchronization. MPI requires the underlying communication network to be perfect - a single message drop causes the training to fail. This is usually achieved via a highly reliable special-purpose network like NCCL.

The XGBoost supports federated paradigm, where clients are in different locations and communicate with each other with gRPC over internet connections.

Currently XGBoost is integrated with FLARE loosely, where FLARE serves as a launchpad to start the XGBoost system. Once started, the XGBoost system runs independently of FLARE, as illustrated in the following figure.

<img width="594" alt="Screenshot 2024-03-05 at 4 04 31 PM" src="https://github.com/NVIDIA/NVFlare/assets/13113932/5d1ac4bc-ef6c-4361-87fd-7ccfa066cf9b">

There are a few potential problems with this approach:

- As we know, MPI requires a perfect communication network, whereas the simple gRPC over the internet could be unstable.

- For every job, the XGB Server needs to initiate a port for XGB clients to connect to. This places a burden on IT to request an additional port in real-world situations. IT must either permit the opening of numerous ports or, if only a fixed port is allowed to open, multiple XGBoost jobs cannot run simultaneously. This is because each XGBoost job requires a unique port number.

**Describe the solution you'd like**
Propose to use FLARE as the XGBoost communicator:

<img width="542" alt="Screenshot 2024-03-05 at 5 23 49 PM" src="https://github.com/NVIDIA/NVFlare/assets/13113932/17be46f7-4c59-4fd2-9518-7fb1a7a79103">

**Describe alternatives you've considered**
We decide to use a python side adaptor to intercept and forward the gRPC requests from XGBoost C++ to python and vice versa.
An alternative is to implement the interface that XGBoost provides in C++.
We opted for the Python approach as it allows us to have control over our release timeline.

**Additional context**

```[tasklist]
### Tasks
- [ ] #2382
- [ ] https://github.com/NVIDIA/NVFlare/pull/2392
- [ ] https://github.com/NVIDIA/NVFlare/pull/2394
- [ ] https://github.com/NVIDIA/NVFlare/pull/2446
- [ ] https://github.com/NVIDIA/NVFlare/pull/2452
- [ ] https://github.com/NVIDIA/NVFlare/pull/2471
```
